# Generated by Django 4.1.7 on 2023-05-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawAiServer', '0002_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
