# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'lawAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lawAI
  pod 'Alamofire'
  pod 'KeychainAccess' 

  target 'lawAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lawAIUITests' do
    # Pods for testing
  end

end
