# Generated by Django 4.2.1 on 2023-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_user_message',
            field=models.BooleanField(default=True),
        ),
    ]
